http:
  port: 8080

admin:
  port: 9876
  host: localhost

serviceEndpoints:
  github:
    url: "https://api.github.com"
  cep:
    url: "https://brasilapi.com.br/api"

apiEndpoints:
  github_api:
    host: "localhost"
    paths:
      - "*"

  cep_api:
    host: "localhost"
    paths:
      - "*"

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - github_api
      - cep_api
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "HEAD,OPTIONS,GET,PUT,POST,DELETE"
      - proxy:
          - condition:
              name: pathMatch
              pattern: "/users/*"
            action:
              serviceEndpoint: github
          - condition:
              name: pathMatch
              pattern: "/cep/*"
            action:
              serviceEndpoint: cep
